[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[flake8]
exclude = "docs"
ignore = "E501,F401,E128,E231,E124"
style = "numpy"

[tool.pytest.ini_options]
collect_ignore = "['setup.py']"

[tool.pycodestyle]
count = false
ignore = "W191,W291,W293,E231,E225"
max-line-length = 160
statistics = false

[project.urls]
Homepage = "https://github.com/JohannesBuchner/PosteriorStacker"
Source = "https://github.com/JohannesBuchner/PosteriorStacker"
Documentation = "https://github.com/JohannesBuchner/PosteriorStacker"
